#pragma once
#include "CoreMinimal.h"

SIRKNIGHT_API DECLARE_LOG_CATEGORY_EXTERN(LogSKCharacterMovement, All, All);
SIRKNIGHT_API DECLARE_LOG_CATEGORY_EXTERN(LogSKCharacterComponent, All, All);

SIRKNIGHT_API DECLARE_LOG_CATEGORY_EXTERN(LogSKInteractions, All, All);

SIRKNIGHT_API DECLARE_LOG_CATEGORY_EXTERN(LogSKUserInterface, All, All);

SIRKNIGHT_API DECLARE_LOG_CATEGORY_EXTERN(LogSKAbilitySystem, All, All);

SIRKNIGHT_API DECLARE_LOG_CATEGORY_EXTERN(LogSKInput, All, All);